language: python

python:
  - '3.6'
  - 'nightly'

sudo: false

cache: pip

addons:
  apt:
    packages:
      - libleveldb-dev

install:
  - ./setup.py develop
  - pip install --quiet coveralls pylint mypy

script:
  - coverage run --source levelorm -m unittest --verbose
  - 'pylint levelorm tests *.py'
  - mypy levelorm tests
  - ./setup.py check --strict

after_success:
  coveralls

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - 'irc.rizon.net#raylu'
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}'
